language: node_js
node_js:
- 12.16.1
dist: bionic
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_651986ed9517_key -iv $encrypted_651986ed9517_iv
  -in strapi-deploy.enc -out strapi-deploy -d
- cd backend
