language: node_js
node_js:
  - 12.16.1

dist: bionic
sudo: false

addons:
  ssh_known_hosts:
    - 45.33.76.67

before_install:
- cd backend
- openssl aes-256-cbc -K $encrypted_651986ed9517_key -iv $encrypted_651986ed9517_iv
  -in scripts/strapi-deploy.enc -out scripts/strapi-deploy -d
- eval "$(ssh-agent -s)"
- cp scripts/strapi-deploy ~/.ssh/strapi-deploy
- chmod 600 ~/.ssh/strapi-deploy
- ssh-add ~/.ssh/strapi-deploy
- echo -e "Host 45.33.76.67\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: main